### ISSUE TITLE
How to disable loading spinner in code ?

### ISSUE THREAD

**Issue by KOSSOKO** [jagomf/countries-map#12]
Hello,
After installing the plugin, i have this spinner loading in the middle of the screen infinitely.
I have to click on a country to stop and remove the spinner.
How could i disable it dynamically in the code ? There are nothing about this spinner in the documentation.

Thanks
![image](https://user-images.githubusercontent.com/11942543/100805242-9fdaf900-342e-11eb-8241-e7437f565530.png)

**Comment by jagomf** [comment]
We do not provide any spinner, only the "Loading map..." text.
It gets automatically hidden (as per the `*ngIf` in [`projects/lib/src/lib/countries-map.component.html` line 1](https://github.com/jagomf/countries-map/blob/master/projects/lib/src/lib/countries-map.component.html#L1)) as soon as the map is loaded.

If you need to hide something manually, you can do it when the `chartReady` event is fired:

```html
<countries-map (chartReady)="hideYourSpinner()"></countries-map>
```
