### ISSUE TITLE
country names not showing on the map

### ISSUE THREAD

**Issue by wajaiye** [jagomf/countries-map#36]
the map does not show the name of the country even though my data specifies it

  mapData: CountriesData = {
    'US': { 'value': 225, 'extra': { 'countryLabel': 'United States', 'showCaption': 'true' } }

  };

<countries-map *ngIf="progress" [data]="mapData" (chartSelect)="select($event)" (chartError)="error($event)" (chartReady)="ready()">

</countries-map>

**Comment by jagomf** [comment]
Attributes `countryLabel` and `showCaption` belong to the component and not to `CountriesData` interface:

```typescript
mapData: CountriesData = {
  'US': { 'value': 225 }
};
```

```html
<countries-map *ngIf="progress" [data]="mapData" (chartSelect)="select($event)" (chartError)="error($event)" (chartReady)="ready()" countryLabel="Country data" [showCaption]="true">
```

Attribute `countryLabel` might have a misleading name; it just sets a label on top of the data selected for countries. Please check demo project embedded in src/app.
