### ISSUE TITLE
Include CountryExtraData in ChartSelectEvent

### ISSUE THREAD

**Issue by vpeter1119** [jagomf/countries-map#46]
I'm trying to use the custom `CountryExtraData` I added in the function I'm executing when a country is selected, however, I noticed that only `selected`, `value` and `country` are included in the event. I think it would be useful to add the extra to the event data so we can use that in the event handler function.

**Comment by jagomf** [comment]
Will further look into it.

**Comment by jagomf** [comment]
Introduced in the codebase -- to be included in next v4 release
